name: ml_is
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - jupyter_client
  - jupyter_contrib_nbextensions
  - matplotlib
  - nltk
  - pandas
  - python=3.6
  - scikit-learn
  - seaborn
